apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2
  template:
    metadata:
      labels:
        app: spring
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: spring
          image: replace
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: NodePort
  selector:
    app: spring
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
